// <auto-generated />
using MVCDEMO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MvcDeMo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211122022529_hj")]
    partial class hj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MVCDEMO.Models.Chidoan", b =>
                {
                    b.Property<string>("cdid")
                        .HasColumnType("TEXT");

                    b.Property<string>("tenchidoan")
                        .HasColumnType("TEXT");

                    b.HasKey("cdid");

                    b.ToTable("Chidoans");
                });

            modelBuilder.Entity("MVCDEMO.Models.Doanvien", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("cdid")
                        .HasColumnType("TEXT");

                    b.Property<string>("chidoancdid")
                        .HasColumnType("TEXT");

                    b.Property<string>("fullname")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("chidoancdid");

                    b.ToTable("Doanvien");
                });

            modelBuilder.Entity("MVCDEMO.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("MVCDEMO.Models.Person", b =>
                {
                    b.Property<string>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MVCDEMO.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MVCDEMO.Models.Student", b =>
                {
                    b.HasBaseType("MVCDEMO.Models.Person");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MVCDEMO.Models.Doanvien", b =>
                {
                    b.HasOne("MVCDEMO.Models.Chidoan", "chidoan")
                        .WithMany()
                        .HasForeignKey("chidoancdid");

                    b.Navigation("chidoan");
                });

            modelBuilder.Entity("MVCDEMO.Models.Student", b =>
                {
                    b.HasOne("MVCDEMO.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("MVCDEMO.Models.Student", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
